# Generated by Django 4.2.8 on 2024-06-11 15:45

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Название картины')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('new_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новая цена')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер скидки')),
                ('new', models.BooleanField(verbose_name='Новинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание картины')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сорт.')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='PaintingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=gallery.models.image_directory_path, verbose_name='Фото')),
                ('image_painting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='painting_gallery', to='gallery.painting', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Фотография картины',
                'verbose_name_plural': 'Фотографии картины',
                'ordering': ['id'],
            },
        ),
    ]
