# Generated by Django 4.2.8 on 2024-06-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название картины'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='paintingimages',
            name='image_painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_gallery', to='gallery.painting', verbose_name='Картина'),
        ),
    ]
