# Generated by Django 4.2.8 on 2024-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_painting_name_alter_painting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
