# Generated by Django 4.2.8 on 2024-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_painting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='url',
            field=models.CharField(blank=True, verbose_name='Url'),
        ),
    ]
