# Generated by Django 4.2.8 on 2024-06-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_painting_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='url',
            new_name='slug',
        ),
    ]
