# Generated by Django 4.2.8 on 2024-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_url_painting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(max_length=170, verbose_name='Название картины'),
        ),
    ]
