# Generated by Django 4.2.8 on 2024-06-13 09:11

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_painting_artist_alter_painting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание картины'),
        ),
    ]
