# Generated by Django 4.2.8 on 2024-06-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_painting_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=170, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=170, null=True, verbose_name='Email')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('requested_painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_requests', to='gallery.painting', verbose_name='Предмет запроса')),
            ],
            options={
                'verbose_name': 'Запрос на приобретение',
                'verbose_name_plural': 'Запросы на приобретение',
                'ordering': ['id'],
            },
        ),
    ]
