# Generated by Django 4.2.8 on 2024-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_paintingrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingrequests',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон'),
        ),
    ]
