# Generated by Django 4.2.8 on 2024-06-13 17:08

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_paintingrequests_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['my_order'], 'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
        migrations.AlterModelOptions(
            name='paintingimages',
            options={'ordering': ['id'], 'verbose_name': 'Фотография лота', 'verbose_name_plural': 'Фотографии лотов'},
        ),
        migrations.AddField(
            model_name='painting',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Активный лот'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание лота'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(max_length=170, verbose_name='Название лота'),
        ),
        migrations.AlterField(
            model_name='paintingimages',
            name='image_painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_gallery', to='gallery.painting', verbose_name='Лот'),
        ),
        migrations.AlterField(
            model_name='paintingrequests',
            name='requested_painting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='painting_requests', to='gallery.painting', verbose_name='Предмет запроса'),
        ),
    ]
