# Generated by Django 4.2.8 on 2024-06-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_alter_painting_options_alter_paintingimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintingrequests',
            options={'ordering': ['-id'], 'verbose_name': 'Запрос на приобретение', 'verbose_name_plural': 'Запросы на приобретение'},
        ),
    ]
