# Generated by Django 4.2.8 on 2024-06-22 22:38

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_paintingrequests_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('text_position', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='right', verbose_name='Расположение текста')),
                ('image', models.ImageField(max_length=255, upload_to=gallery.models.banner_directory_path, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный баннер')),
                ('link_1_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ссылки 1')),
                ('link_1_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка 1')),
                ('link_2_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ссылки 2')),
                ('link_2_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка 2')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
