# Generated by Django 4.2.8 on 2024-06-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название стрима')),
                ('url', models.CharField(max_length=80, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная страница')),
            ],
            options={
                'verbose_name': 'Стрим',
                'verbose_name_plural': 'Стримы',
            },
        ),
    ]
