# Generated by Django 4.2.8 on 2024-06-24 20:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('name', models.CharField(max_length=80, verbose_name='Название страницы')),
                ('slug', models.CharField(max_length=80, verbose_name='url')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная страница')),
                ('is_doc', models.BooleanField(default=True, verbose_name='Страница документа')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сорт.')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['my_order'],
            },
        ),
    ]
