# Generated by Django 4.2.8 on 2024-06-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['my_order'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сорт.'),
        ),
    ]
