# Generated by Django 4.2.8 on 2024-06-12 09:52

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_page_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=80, verbose_name='url'),
        ),
    ]
