# Generated by Django 4.2.8 on 2024-06-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_description_alter_page_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_doc',
            field=models.BooleanField(default=True, verbose_name='Страница документа'),
        ),
    ]
