# Generated by Django 4.2.8 on 2024-06-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_is_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='slug',
        ),
    ]
