# Generated by Django 4.2.8 on 2024-06-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_url_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
